inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

require:
  - rubocop-ast
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'spec/**/*'

RSpec/ContextWording:
  Enabled: false