inherit_from: .rubocop_todo.yml

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

require:
  - rubocop-ast
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'lib/tasks/auto_annotate_models.rake'